# Gazebo ROS Control plugin parameters for the robot
gazebo_ros_control:
  pid_gains:
    wheel_fl_joint:
      p: 2.0
      i: 1.0
      d: 1.0
    wheel_ml_joint:
      p: 2.0
      i: 1.0
      d: 1.0
    wheel_rl_joint:
      p: 2.0
      i: 1.0
      d: 1.0
    wheel_fr_joint:
      p: 2.0
      i: 1.0
      d: 1.0
    wheel_mr_joint:
      p: 2.0
      i: 1.0
      d: 1.0
    wheel_rr_joint:
      p: 2.0
      i: 1.0
      d: 1.0

